In [2]:
import numpy as np
import math

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# write a function that do QR decomposition
def QR_Decomposition(A):
    m,n = A.shape
    Q = np.identity(m)
    R = A
    for i in range(n):
        H = np.identity(m)
        x = R[i:,i]
        e = np.zeros_like(x)
        e[0] = 1
        u = np.sign(x[0])*np.linalg.norm(x)*e + x
        u = u/np.linalg.norm(u)
        H[i:,i:] -= 2*np.outer(u,u)
        Q = np.dot(Q,H)
        R = np.dot(H,R)
    return Q,R

QR_Decomposition(np.array([[1,2,3],[4,5,5],[7,8,1]]))

(array([[-0.12309149,  0.90453403, -0.40824829],
        [-0.49236596,  0.30151134,  0.81649658],
        [-0.86164044, -0.30151134, -0.40824829]]),
 array([[-8.12403840e+00, -9.60113630e+00, -3.69274473e+00],
        [-8.42222460e-16,  9.04534034e-01,  3.91964748e+00],
        [ 6.44518747e-16, -2.17887053e-17,  2.44948974e+00]]))

In [14]:
def Jacobi(A,eps):
    n = len(A)
    
    # initialize the eigenvector matrix
    V = np.identity(n)
    
    # maximum off-diagonal element
    maxoff = 1
    
    # number of iterations
    k = 0
    
    # while the maximum off-diagonal element is larger than the tolerance
    while maxoff > eps:
        # find the maximum off-diagonal element
        maxoff = 0
        for i in range(n):
            for j in range(i+1,n):
                if abs(A[i,j]) > maxoff:
                    maxoff = abs(A[i,j])
                    p = i
                    q = j
        
        # calculate the angle of rotation
        if A[p,p] == A[q,q]:
            theta = math.pi/4
        else:
            theta = 0.5*math.atan(2*A[p,q]/(A[p,p]-A[q,q]))
        
        # calculate the rotation matrix
        U = np.identity(n)
        U[p,p] = math.cos(theta)
        U[p,q] = -math.sin(theta)
        U[q,p] = math.sin(theta)
        U[q,q] = math.cos(theta)
        
        
        # update the eigenvector matrix
        V = V.dot(U)
        # update the matrix A
        A = U.T.dot(A).dot(U)
        # update the number of iterations
        k += 1
    
    # eigenvalues
    eig = np.zeros(n)
    for i in range(n):
        eig[i] = A[i,i]
    # return the eigenvalues, eigenvector matrix, and the number of iterations
    return eig,V,k


In [25]:
A = np.array([
 [3, 2, 5, 4, 6],
 [2, 1, 3, -7, 8],
 [5, 3, 2, 5, -4],
 [4, -7, 5, 1, 3],
 [6, 8, -4, 3, 8]
])
eps = 1e-6
a, V, k = Jacobi(A, eps)

for i in range(len(a)):
    print("eigenvalue: ",a[i], " eigenvector: ", V[:,i])

print("\nThe number of iterations is:")
print(k)

eigenvalue:  -4.061950892717062  eigenvector:  [ 0.76863992 -0.2216914  -0.36928326 -0.3954453  -0.25941952]
eigenvalue:  -12.76055498964532  eigenvector:  [ 0.08924015  0.59143517 -0.44077046  0.52545854 -0.41455442]
eigenvalue:  11.023392437654193  eigenvector:  [ 0.41186619 -0.34298863  0.54290688  0.61554366 -0.19769463]
eigenvalue:  4.574951567326781  eigenvector:  [-0.10396914 -0.54629807 -0.60711145  0.42239939  0.37913491]
eigenvalue:  16.22416187738141  eigenvector:  [0.46987821 0.43008672 0.07758273 0.10100048 0.76027607]

The number of iterations is:
29
